### PR TITLE
Allow jsx values in argument notation when using format-icu

### PR DESCRIPTION
**Pull request by kalimantos**
#3219

### CODE REVIEW

**Comment by stepan662** [comment]
Hey, thank you for your effort. I get that it solves your problem, but this is not good for maintenance. Would it be possible for you to release this as e.g. separate npm package? You are not changing anything in the tolgee core, so it should be possible to release this as a plugin in a package.

**Comment by kalimantos** [comment]
Thank you @stepan662 for the response, you mean the entire format-icu as a separate tolgee plugin or just the edited `intl-messageformat`?

**Comment by stepan662** [comment]
I mean just making an alternative package e.g. `tolgee-format-icu-jsx-param` (or some better name) which will be used the same way as format-icu, but with the support for the interpolation.

**Comment by stepan662** [comment]
Cool, thank you :)

**Comment by JanCizmar** [comment]
Anyway, thanks for this contribution, when you're done, we can add mention of your package to the docs.

**Comment by kalimantos** [comment]
Awesome thank you, i'll notice you when is ready

**Comment by kalimantos** [comment]
Finally, here it is https://github.com/Artshell-company/tolgee-format-icu-jsx-param

**Pull request closed without merging**
